# Project information
site_name: Prismatopia
site_description: Prismatopia documentation
site_author: Bernie Durfee (Lambda School Labs)

# Repository
repo_name: Lambda-School-Labs/prismadocia
repo_url: https://github.com/Lambda-School-Labs/prismadocia

# Copyright
copyright: © Lambda School

# Configuration
theme:
  name: 'material'
  logo: images/Lambda_Shield_Red.png
  language: en

extra_css:
  - stylesheets/extra.css

markdown_extensions:
    - tables
    - admonition
    - toc:
        permalink: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite
    # - pymdownx.highlight:
    #     guess_lang: false
    #     pygments_style: colorful
    #     noclasses: true

nav:
    - Overview: 'index.md'
    - Apollo Layer: 'apollo.md'
    - Prisma Layer: 'prisma.md'
    - AWS Layer: 'aws.md'
    - About: 'about.md'
