name: Lint all the Markdown!
on:
  - pull_request

jobs:
  build:
    name: Lint the Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v1

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Run markdownlint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: ".markdownlint.yml"
